Repository GrumpyCrouton/SDV-AccessibleTiles, pull requests merged in 2022-02, with the labels that each got.

#6 withering crops
  TrackingMode/TrackerUtility.cs
Labels: bug

#7 Pathfinding
  ModEntry.cs
  README.md
  TrackingMode/Tracker.cs
  TrackingMode/TrackerUtility.cs
  manifest.json
Labels: documentation, enhancement

#13 Bugged warps
  TrackingMode/Tracker.cs
  TrackingMode/TrackerUtility.cs
  manifest.json
Labels: bug

#17 Add logic to track machine states
  TrackingMode/TrackerUtility.cs
Labels: enhancement

#18 Various issues
  ModEntry.cs
  TrackingMode/Tracker.cs
  TrackingMode/TrackerUtility.cs
Labels: bug, enhancement

#25 Various Updates 2
  ModEntry.cs
  TrackingMode/Tracker.cs
  TrackingMode/TrackerUtility.cs
Labels: bug, enhancement

#29 Update
  ModEntry.cs
  TrackingMode/Tracker.cs
  TrackingMode/TrackerUtility.cs
  manifest.json
Labels: bug, enhancement
